name: vidae
channels:
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=10.2
  - absl-py
  - pyparsing
  - pip
  - pip:
    - pillow==6.2.0
    - termcolor
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - xmltodict
    - scikit-image
    - seaborn
    - tqdm
    - gym
    - mujoco-py
    - kornia
    - einops
